import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

import org.w3c.dom.Document;
import org.xml.sax.SAXException;

public class Stylizer {
	public static void main (String argv[]) {
		 DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
	        try {
	            File stylesheet = new File("NewStylesheet.xsl");
	            File datafile = new File("weather.xml");

	            DocumentBuilder builder = factory.newDocumentBuilder();
	            Document document = builder.parse(datafile);

	            TransformerFactory tFactory = TransformerFactory.newInstance();
	            StreamSource stylesource = new StreamSource(stylesheet);
	            Transformer transformer = tFactory.newTransformer(stylesource);
	            DOMSource source = new DOMSource(document);
	            StreamResult result = new StreamResult(new FileOutputStream(new File("a.xml")));
	            transformer.transform(source, result);
	        }catch (TransformerConfigurationException tce) {
	            // Error generated by the parser
	            System.out.println("\n** Transformer Factory error");
	            System.out.println("   " + tce.getMessage());

	            // Use the contained exception, if any
	            Throwable x = tce;

	            if (tce.getException() != null) {
	                x = tce.getException();
	            }

	            x.printStackTrace();
	        } catch (TransformerException te) {
	            // Error generated by the parser
	            System.out.println("\n** Transformation error");
	            System.out.println("   " + te.getMessage());

	            // Use the contained exception, if any
	            Throwable x = te;

	            if (te.getException() != null) {
	                x = te.getException();
	            }

	            x.printStackTrace();
	        } catch (SAXException sxe) {
	            // Error generated by this application
	            // (or a parser-initialization error)
	            Exception x = sxe;

	            if (sxe.getException() != null) {
	                x = sxe.getException();
	            }

	            x.printStackTrace();
	        } catch (ParserConfigurationException pce) {
	            // Parser with specified options can't be built
	            pce.printStackTrace();
	        } catch (IOException ioe) {
	            // I/O error
	            ioe.printStackTrace();
	        }
	    }
}
