//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:00:52 AM CEST 
//


package com.unister.semweb.apiontology.zipcodes.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.unister.semweb.spring.ws.test.schema.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.unister.semweb.spring.ws.test.schema.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetZipcodeRequest }
     * 
     */
    public GetZipcodeRequest createGetZipcodeRequest() {
        return new GetZipcodeRequest();
    }

    /**
     * Create an instance of {@link ZipcodeResponse }
     * 
     */
    public ZipcodeResponse createZipcodeResponse() {
        return new ZipcodeResponse();
    }

}
