//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 09:00:52 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.unister.de/zipcode/schema/beans")
package com.unister.semweb.apiontology.zipcodes.domain;
